'use strict';

const os = require('node:os');
const path = require('node:path');

const DATA_DIR = path.join(
  process.env.XDG_DATA_HOME || path.join(os.homedir(), '.local', 'share'),
  'visual-clipboard'
);
const IMAGES_DIR = path.join(DATA_DIR, 'images');
const THUMBS_DIR = path.join(DATA_DIR, 'thumbs');
const HISTORY_FILE = path.join(DATA_DIR, 'history.json');
const CONFIG_FILE = path.join(DATA_DIR, 'config.json');
const AUTOSTART_FILE = path.join(os.homedir(), '.config', 'autostart', 'visual-clipboard.desktop');
const LAUNCHER_FILE = path.join(os.homedir(), '.local', 'bin', 'visual-clipboard');

const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
const MAX_TEXT_CHARS = 2 * 1024 * 1024;
const POLL_MS = 500;
const PREVIEW_CHARS = 300;
const PANEL_HEIGHT = 320;
const THUMB_HEIGHT = 240;
const THUMB_WIDTH = 480;

const MAX_IGNORE_PATTERNS = 50;

// Chromium ships inside Electron and this renderer decodes images strangers put on the
// clipboard. The sandbox contains a decoder bug; only an upgrade removes it. Roughly a
// quarter of a year without one is worth a tray warning.
const ELECTRON_STALE_DAYS = 90;

const GNOME_FILES_FORMAT = 'x-special/gnome-copied-files';
// clipboard targets password managers set to mark a selection as "do not record"
const SECRET_HINT_FORMATS = new Set([
  'x-kde-passwordManagerHint',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
]);
const VIDEO_EXTS = new Set(['mp4', 'webm', 'mkv', 'mov', 'avi', 'm4v']);
const IMAGE_EXTS = new Set(['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'avif']);
const BOARD_COLORS = ['#32D74B', '#0A84FF', '#FF9F0A', '#BF5AF2', '#FF375F', '#64D2FF', '#30D5C8'];

const DEFAULT_CONFIG = {
  shortcut: 'Control+Alt+V',
  maxItems: 500,
  autoPaste: true,
  pasteDelayMs: 150,
  display: 'cursor',
  paused: false,
  ignorePatterns: [],
};

const DEBUG = !!process.env.CLP_DEBUG;

module.exports = {
  DATA_DIR, IMAGES_DIR, THUMBS_DIR, HISTORY_FILE, CONFIG_FILE, AUTOSTART_FILE, LAUNCHER_FILE,
  MAX_IMAGE_BYTES, MAX_TEXT_CHARS, POLL_MS, PREVIEW_CHARS, PANEL_HEIGHT,
  THUMB_HEIGHT, THUMB_WIDTH, MAX_IGNORE_PATTERNS, ELECTRON_STALE_DAYS,
  GNOME_FILES_FORMAT, SECRET_HINT_FORMATS, VIDEO_EXTS, IMAGE_EXTS, BOARD_COLORS,
  DEFAULT_CONFIG, DEBUG,
};
