'use strict';

const os = require('node:os');
const path = require('node:path');

const DATA_DIR = path.join(
  process.env.XDG_DATA_HOME || path.join(os.homedir(), '.local', 'share'),
  'visual-clipboard'
);
const IMAGES_DIR = path.join(DATA_DIR, 'images');
const THUMBS_DIR = path.join(DATA_DIR, 'thumbs');
const HISTORY_FILE = path.join(DATA_DIR, 'history.json');
const CONFIG_FILE = path.join(DATA_DIR, 'config.json');
const AUTOSTART_FILE = path.join(os.homedir(), '.config', 'autostart', 'visual-clipboard.desktop');
const LAUNCHER_FILE = path.join(os.homedir(), '.local', 'bin', 'visual-clipboard');
/** Marks an exit as deliberate so the launcher's supervisor stops instead of respawning. */
const QUIT_FLAG = path.join(DATA_DIR, 'quitting');
/** Touched every heartbeat; its mtime is the only main-thread liveness proof readable from outside. */
const HEARTBEAT_FILE = path.join(DATA_DIR, 'alive');

const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
const MAX_TEXT_CHARS = 2 * 1024 * 1024;
const POLL_MS = 500;
const PREVIEW_CHARS = 300;
const PANEL_HEIGHT = 320;
const THUMB_HEIGHT = 240;
const THUMB_WIDTH = 480;

const MAX_IGNORE_PATTERNS = 50;

const HEARTBEAT_MS = 60000;
/** A clipboard read slower than this blocked the main process — gets its own log line. */
const POLL_SLOW_MS = 1000;
/** Exit code the restart button uses: non-zero so the supervisor respawns. */
const RESTART_CODE = 42;
/** Seconds Reiniciar and Sair wait for a graceful shutdown before the detached killer fires. */
const EXIT_GRACE_S = 5;
/** Seconds without a heartbeat before the watchdog SIGKILLs; 0 disables it. Never go under 120. */
const WATCHDOG_S = Number(process.env.CLP_WATCHDOG_S ?? 180);

/** Days since the last Electron install before the tray warns about stale Chromium. */
const ELECTRON_STALE_DAYS = 90;

const GNOME_FILES_FORMAT = 'x-special/gnome-copied-files';
/** Clipboard targets password managers set to mark a selection as "do not record". */
const SECRET_HINT_FORMATS = new Set([
  'x-kde-passwordManagerHint',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
]);
const VIDEO_EXTS = new Set(['mp4', 'webm', 'mkv', 'mov', 'avi', 'm4v']);
const IMAGE_EXTS = new Set(['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'avif']);
const BOARD_COLORS = ['#32D74B', '#0A84FF', '#FF9F0A', '#BF5AF2', '#FF375F', '#64D2FF', '#30D5C8'];

const DEFAULT_CONFIG = {
  shortcut: 'Control+Alt+V',
  maxItems: 500,
  autoPaste: true,
  pasteDelayMs: 150,
  display: 'cursor',
  paused: false,
  ignorePatterns: [],
};

const DEBUG = !!process.env.CLP_DEBUG;

module.exports = {
  DATA_DIR, IMAGES_DIR, THUMBS_DIR, HISTORY_FILE, CONFIG_FILE, AUTOSTART_FILE, LAUNCHER_FILE,
  QUIT_FLAG, HEARTBEAT_FILE, EXIT_GRACE_S, WATCHDOG_S, MAX_IMAGE_BYTES, MAX_TEXT_CHARS, POLL_MS, PREVIEW_CHARS, PANEL_HEIGHT,
  THUMB_HEIGHT, THUMB_WIDTH, MAX_IGNORE_PATTERNS, ELECTRON_STALE_DAYS,
  HEARTBEAT_MS, POLL_SLOW_MS, RESTART_CODE,
  GNOME_FILES_FORMAT, SECRET_HINT_FORMATS, VIDEO_EXTS, IMAGE_EXTS, BOARD_COLORS,
  DEFAULT_CONFIG, DEBUG,
};
